# Production URL (dùng khi deploy)
baseURL = "https://duongbinhminh1003.github.io/dbm1003/"
publishDir = "public"

# ❗ TẮT cho multilingual + Relearn
canonifyURLs = true
relativeURLs = false

title = "AWS Internship"
theme = "relearn"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

# ------------------------------------------------
# Outputs (search cho Relearn)
# ------------------------------------------------
[outputs]
home = ["HTML", "RSS", "JSON"]

# ------------------------------------------------
# Params (Relearn theme)
# ------------------------------------------------
[params]
  showLanguageSelector = true
  themeVariant = ["relearn-light", "relearn-dark"]
  alwaysShowThemeSwitcher = true
  collapseLevel = 4
  customCSS = ["css/custom.css"]

# ------------------------------------------------
# Languages
# ------------------------------------------------
[languages]
  [languages.en]
    title = "Internship Report"
    languageName = "English"
    languageCode = "en"
    weight = 1

  [languages.vi]
    title = "Báo Cáo Thực Tập"
    languageName = "Tiếng Việt"
    languageCode = "vi"
    weight = 2

# ------------------------------------------------
# Markup
# ------------------------------------------------
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true