name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - master   # nhánh bạn làm việc

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo và submodules
      - uses: actions/checkout@v4
        with:
          submodules: true   # quan trọng nếu dùng theme relearn submodule

      # Cài Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v5
        with:
          hugo-version: '0.111.3'  # thay version nếu cần

      # Build Hugo site
      - name: Build
        run: hugo --minify

      # Deploy thư mục public/ lên GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
